name: Deploy
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    name: Deploy on TestFlight 
    runs-on: macos-11
      
    steps:      
    - name: Checkout
      uses: actions/checkout@v2

    - uses: webfactory/ssh-agent@v0.5.3
      with:
          ssh-private-key: ${{ secrets.MATCH_SSH_KEY }}

    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 13.0
    
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
            
    - name: Build & Deploy
      run: |
        bundle exec fastlane deploy build_number:$BUILD_NUMBER
      env:
        MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
        FASTLANE_KEY_ID: '${{ secrets.FASTLANE_KEY_ID }}'
        FASTLANE_ISSUER_ID: '${{ secrets.FASTLANE_ISSUER_ID }}'
        FASTLANE_API_KEY: '${{ secrets.FASTLANE_API_KEY }}'
        BUILD_NUMBER: '${{ github.run_id }}'